"use strict";
function await ( x , ... [ ] ) { } 

Test fail for `babel`: 7042.js
TAG: NEW-RENAMED-AWAIT
[Assertion Fail]
 > Expected [object Function] but got undefined.
Expected true but got false.
Expected undefined has [[Call]] but does not.
Expected undefined has [[Construct]] but does not.
$assert.compareArray requires an array as the first argument but undefined given.
Expected the object prototype but got undefined.
Expected true but got false.
$assert.compareArray requires an array as the first argument but undefined given.
$verifyProperty requires an object but undefined given.
$verifyProperty requires an object but undefined given.
$verifyProperty requires an object but undefined given.
$verifyProperty requires an object but undefined given.
